spring:
  application:
    name: multi-dc-app
  
  # Primary DataSource Configuration
  datasource:
    url: jdbc:postgresql://primary-dc:5432/mydb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  
  # Secondary DataSource Configuration
  second-datasource:
    url: jdbc:postgresql://secondary-dc:5432/mydb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# Pulsar Configuration
pulsar:
  service-url: pulsar://localhost:6650
  admin-url: http://localhost:8080
  client:
    operationTimeoutMs: 30000
    connectionTimeoutMs: 30000
    enableTcpNoDelay: true
    keepAliveIntervalSeconds: 20
    enableBatching: true
    batchingMaxPublishDelayMicros: 1000
    batchingMaxMessages: 1000

# Datacenter Configuration
datacenter:
  id: dc1

# Debezium Configuration
debezium:
  connector:
    name: postgres-connector
    database:
      hostname: localhost
      port: 5432
      user: debezium
      password: debezium
      dbname: multidc
      server:
        name: ${datacenter.id}
    schema:
      include-list: public
    table:
      include-list: public.users
  topic:
    prefix: ${datacenter.id}.public

# Logging Configuration
logging:
  level:
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[com.example.multidc]': DEBUG 